# Generated by Django 3.1 on 2020-10-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=70)),
                ('image_url', models.URLField(blank=True)),
                ('address', models.CharField(max_length=100)),
                ('client_type', models.CharField(choices=[('NORMAL', 'NORMAL'), ('PLATA', 'PLATA'), ('ORO', 'ORO'), ('PLATINO', 'PLATINO')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_products', to='app.product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_products', to='app.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30)),
                ('order_date', models.DateTimeField()),
                ('deliver_date', models.DateTimeField()),
                ('priority', models.BooleanField(default=False)),
                ('items', models.IntegerField(default=0)),
                ('order_type', models.CharField(choices=[('CEDIS', 'CEDIS'), ('SUCURSAL', 'SUCURSAL'), ('EMPRESA_ASOCIADA', 'EMPRESA_ASOCIADA')], max_length=20)),
                ('distribution_center_store', models.CharField(blank=True, max_length=50)),
                ('store_reference', models.CharField(blank=True, max_length=100)),
                ('store_code', models.CharField(blank=True, max_length=30)),
                ('company_reference', models.CharField(blank=True, max_length=100)),
                ('company_member_code', models.CharField(blank=True, max_length=30)),
                ('company_order_detail', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.provider')),
            ],
        ),
    ]
